# Generated by Django 5.0.14 on 2026-09-03 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_url", models.URLField(max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Analyzing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("seniority_level", models.CharField(blank=True, max_length=100)),
                ("summary", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "work_arrangement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("remote", "Remote"),
                            ("hybrid", "Hybrid"),
                            ("onsite", "On-site"),
                            ("unclear", "Not specified"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timezone_expectations", models.CharField(blank=True, max_length=200)),
                ("relocation_offered", models.BooleanField(blank=True, null=True)),
                ("travel_percentage", models.CharField(blank=True, max_length=100)),
                ("salary_min", models.PositiveIntegerField(blank=True, null=True)),
                ("salary_max", models.PositiveIntegerField(blank=True, null=True)),
                ("salary_currency", models.CharField(blank=True, max_length=10)),
                (
                    "salary_period",
                    models.CharField(
                        blank=True, help_text="e.g. year, hour", max_length=20
                    ),
                ),
                ("compensation_notes", models.TextField(blank=True)),
                (
                    "benefits",
                    models.TextField(blank=True, help_text="One benefit per line."),
                ),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("company_size", models.CharField(blank=True, max_length=100)),
                ("company_stage", models.CharField(blank=True, max_length=100)),
                ("company_industry", models.CharField(blank=True, max_length=150)),
                ("company_mission", models.TextField(blank=True)),
                ("reports_to", models.CharField(blank=True, max_length=150)),
                ("application_instructions", models.TextField(blank=True)),
                ("application_deadline", models.CharField(blank=True, max_length=100)),
                (
                    "red_flags",
                    models.TextField(blank=True, help_text="One red flag per line."),
                ),
                ("growth_language_notes", models.TextField(blank=True)),
                ("diversity_statement", models.TextField(blank=True)),
                ("raw_text", models.TextField(blank=True)),
                (
                    "manual_text",
                    models.TextField(
                        blank=True,
                        help_text="Job description pasted by hand instead of fetched from the URL.",
                    ),
                ),
                ("ai_model", models.CharField(blank=True, max_length=100)),
                ("fetched_at", models.DateTimeField(blank=True, null=True)),
                ("analyzed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RequirementCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("responsibilities", "Responsibilities"),
                            ("required", "Required qualifications"),
                            ("preferred", "Preferred qualifications"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="jobs.jobpost",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "requirement categories",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="jobs.requirementcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
