# Generated by Django 5.0.14 on 2026-09-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="profile_matched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="requirement",
            name="match_evidence",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="requirement",
            name="match_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("strong", "Strong match"),
                    ("partial", "Partial match"),
                    ("none", "Not covered"),
                ],
                max_length=10,
            ),
        ),
    ]
