# Generated by Django 5.0.14 on 2026-09-10 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_jobpost_profile_matched_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requirementcategory",
            name="job",
        ),
        migrations.AddField(
            model_name="jobpost",
            name="analysis_language",
            field=models.CharField(
                blank=True,
                help_text="Language the AI was asked to answer in, so a re-render never mixes languages.",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="JobSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("overview", "Overview"),
                            ("company", "Company"),
                            ("location_arrangement", "Location & work arrangement"),
                            ("compensation_benefits", "Compensation & benefits"),
                            ("how_to_apply", "How to Apply"),
                            ("responsibilities", "Responsibilities"),
                            ("required_technical_skills", "Required Technical Skills"),
                            (
                                "desirable_technical_skills",
                                "Desirable Technical Skills",
                            ),
                            ("desirable_soft_skills", "Desirable Soft Skills"),
                            ("languages", "Languages"),
                            ("education_certifications", "Education & Certifications"),
                            ("worth_noting", "Worth noting"),
                            ("red_flags", "Possible red flags"),
                        ],
                        max_length=40,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Prose, for sections without element rows.",
                    ),
                ),
                (
                    "match_state",
                    models.CharField(
                        choices=[
                            ("idle", "Not matched yet"),
                            ("running", "Matching…"),
                            ("done", "Matched"),
                            ("failed", "Matching failed"),
                        ],
                        default="idle",
                        max_length=20,
                    ),
                ),
                ("match_error", models.TextField(blank=True)),
                ("matched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="jobs.jobpost",
                    ),
                ),
            ],
            options={
                "verbose_name": "job section",
                "verbose_name_plural": "job sections",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="JobElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "match_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("strong", "Strong match"),
                            ("partial", "Partial match"),
                            ("none", "Not covered"),
                        ],
                        max_length=10,
                    ),
                ),
                ("match_evidence", models.TextField(blank=True)),
                ("evaluated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_evaluating",
                    models.BooleanField(
                        default=False,
                        help_text="True while a single-element re-evaluation is in flight.",
                    ),
                ),
                ("added_to_profile_at", models.DateTimeField(blank=True, null=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elements",
                        to="jobs.jobsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "job element",
                "verbose_name_plural": "job elements",
                "ordering": ["order", "id"],
            },
        ),
        migrations.DeleteModel(
            name="Requirement",
        ),
        migrations.DeleteModel(
            name="RequirementCategory",
        ),
        migrations.AddConstraint(
            model_name="jobsection",
            constraint=models.UniqueConstraint(
                fields=("job", "key"), name="unique_section_per_job"
            ),
        ),
    ]
