# Generated by Django 5.0.14 on 2026-09-10 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AITask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("resume_import", "Resume analysis"),
                            ("job_analysis", "Job analysis"),
                            ("job_match", "Matching analysis"),
                            ("tailored_resume", "Resume generation"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "celery_task_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("steps_total", models.PositiveSmallIntegerField(default=1)),
                ("steps_done", models.PositiveSmallIntegerField(default=0)),
                ("current_step", models.CharField(blank=True, max_length=200)),
                ("error_message", models.TextField(blank=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("queued_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI task",
                "verbose_name_plural": "AI tasks",
                "ordering": ["-queued_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="core_aitask_content_53078e_idx",
                    ),
                    models.Index(
                        fields=["user", "state"], name="core_aitask_user_id_3bf95f_idx"
                    ),
                ],
            },
        ),
    ]
