# Generated by Django 5.0.14 on 2026-09-10 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "desired_salary_min",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Minimum salary"
                    ),
                ),
                (
                    "desired_salary_max",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Target salary"
                    ),
                ),
                (
                    "salary_currency",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Currency"
                    ),
                ),
                (
                    "salary_period",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("year", "Per year"),
                            ("month", "Per month"),
                            ("day", "Per day"),
                            ("hour", "Per hour"),
                        ],
                        default="year",
                        max_length=20,
                        verbose_name="Period",
                    ),
                ),
                (
                    "preferred_locations",
                    models.TextField(
                        blank=True,
                        help_text="One location per line.",
                        verbose_name="Preferred locations",
                    ),
                ),
                (
                    "remote_ok",
                    models.BooleanField(default=False, verbose_name="Open to remote"),
                ),
                (
                    "hybrid_ok",
                    models.BooleanField(default=False, verbose_name="Open to hybrid"),
                ),
                (
                    "onsite_ok",
                    models.BooleanField(default=False, verbose_name="Open to on-site"),
                ),
                (
                    "max_onsite_days_per_week",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Maximum on-site days per week",
                    ),
                ),
                (
                    "willing_to_relocate",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Willing to relocate"
                    ),
                ),
                (
                    "max_travel_percentage",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Maximum travel (%)"
                    ),
                ),
                (
                    "timezone_preference",
                    models.CharField(
                        blank=True,
                        help_text="e.g. “EST ±2h” or “Europe only”",
                        max_length=120,
                        verbose_name="Time zone",
                    ),
                ),
                (
                    "employment_types",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated, e.g. “Full-time, Contract”.",
                        max_length=200,
                        verbose_name="Employment types",
                    ),
                ),
                (
                    "availability_notes",
                    models.TextField(blank=True, verbose_name="Availability"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "job preference",
                "verbose_name_plural": "job preferences",
            },
        ),
        migrations.CreateModel(
            name="BenefitPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Benefit")),
                (
                    "importance",
                    models.CharField(
                        choices=[
                            ("must_have", "Must have"),
                            ("nice_to_have", "Nice to have"),
                            ("not_important", "Not important"),
                        ],
                        default="nice_to_have",
                        max_length=20,
                        verbose_name="Importance",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=250, verbose_name="Notes"),
                ),
                (
                    "preference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefits",
                        to="preferences.jobpreference",
                    ),
                ),
            ],
            options={
                "verbose_name": "benefit preference",
                "verbose_name_plural": "benefit preferences",
                "ordering": ["importance", "name"],
            },
        ),
        migrations.AddConstraint(
            model_name="benefitpreference",
            constraint=models.UniqueConstraint(
                fields=("preference", "name"), name="unique_benefit_per_preference"
            ),
        ),
    ]
