# Generated by Django 5.0.14 on 2026-09-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preferences", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpreference",
            name="max_onsite_days_per_week",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Max. on-site days / week"
            ),
        ),
        migrations.AlterField(
            model_name="jobpreference",
            name="max_travel_percentage",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Max. travel (%)"
            ),
        ),
    ]
