# Generated by Django 5.0.14 on 2026-09-17 03:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=60)),
                ("tagline", models.CharField(blank=True, max_length=150)),
                ("description", models.TextField(blank=True)),
                ("price_cents", models.PositiveIntegerField(default=0)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "interval",
                    models.CharField(
                        choices=[("month", "Monthly"), ("year", "Yearly")],
                        default="month",
                        max_length=10,
                    ),
                ),
                ("trial_days", models.PositiveSmallIntegerField(default=0)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive plans keep their subscribers but take no new ones.",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, help_text="Listed on the pricing page."
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="The plan a new account is put on. Exactly one plan has this.",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("max_profiles", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "monthly_job_analyses",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "monthly_tailored_resumes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "monthly_resume_imports",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "features",
                    models.TextField(
                        blank=True, help_text="One selling point per line."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "price_cents", "id"],
            },
        ),
        migrations.CreateModel(
            name="StaffMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("viewer", "Viewer — read-only"),
                            ("support", "Support — user actions, impersonation, notes"),
                            (
                                "billing",
                                "Billing — support, plus plans and subscriptions",
                            ),
                            (
                                "admin",
                                "Admin — everything except superuser-only actions",
                            ),
                        ],
                        default="viewer",
                        max_length=20,
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Why this person has portal access.",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "staff member",
                "verbose_name_plural": "staff members",
                "ordering": ["user__email"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trialing", "Trialing"),
                            ("active", "Active"),
                            ("past_due", "Past due"),
                            ("canceled", "Canceled"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "current_period_start",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "external_customer_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "external_subscription_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal only — never shown to the customer.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupportNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_email", models.CharField(blank=True, max_length=254)),
                ("body", models.TextField()),
                ("pinned", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=60, unique=True)),
                ("value", models.CharField(blank=True, max_length=500)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("job_analysis", "Job analyses"),
                            ("tailored_resume", "Tailored resumes"),
                            ("resume_import", "Resume imports"),
                        ],
                        max_length=30,
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("count", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-period_start", "metric"],
            },
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("body", models.TextField(blank=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("success", "Success"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("everyone", "Everyone"),
                            ("authenticated", "Signed-in users"),
                            ("staff", "Staff only"),
                        ],
                        default="authenticated",
                        max_length=20,
                    ),
                ),
                ("link_url", models.URLField(blank=True)),
                ("link_label", models.CharField(blank=True, max_length=60)),
                ("is_active", models.BooleanField(default=True)),
                ("dismissible", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-starts_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_email", models.CharField(blank=True, max_length=254)),
                ("action", models.CharField(db_index=True, max_length=60)),
                ("target_type", models.CharField(blank=True, max_length=40)),
                ("target_id", models.CharField(blank=True, max_length=40)),
                ("target_repr", models.CharField(blank=True, max_length=200)),
                ("summary", models.CharField(blank=True, max_length=300)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("while_impersonating", models.BooleanField(default=False)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "audit log entry",
                "verbose_name_plural": "audit log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=60, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("off", "Off for everyone"),
                            ("on", "On for everyone"),
                            ("staff", "Staff only"),
                            ("percent", "Percentage rollout"),
                        ],
                        default="off",
                        max_length=10,
                    ),
                ),
                (
                    "percentage",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Always on for these accounts, whatever the state says.",
                        related_name="forced_feature_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="ImpersonationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_email", models.CharField(blank=True, max_length=254)),
                ("target_email", models.CharField(blank=True, max_length=254)),
                ("reason", models.CharField(max_length=200)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ended_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("manual", "Ended by the operator"),
                            ("expired", "Timed out"),
                            ("logout", "Session ended"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="impersonations_started",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="impersonations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="plan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("is_default",),
                name="only_one_default_plan",
            ),
        ),
        migrations.AddField(
            model_name="featureflag",
            name="plans",
            field=models.ManyToManyField(
                blank=True,
                help_text="Always on for entitled subscribers of these plans.",
                related_name="feature_flags",
                to="staffportal.plan",
            ),
        ),
        migrations.AddField(
            model_name="staffmember",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="staffmember",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_member",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="staffportal.plan",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="supportnote",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="supportnote",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="support_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usagerecord",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usage_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["target_type", "target_id"],
                name="staffportal_target__a1c0c5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["actor", "-created_at"], name="staffportal_actor_i_71e389_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="impersonationsession",
            index=models.Index(
                fields=["target", "-started_at"], name="staffportal_target__e8d862_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["status", "plan"], name="staffportal_status_1138a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usagerecord",
            index=models.Index(
                fields=["metric", "period_start"], name="staffportal_metric_ab344b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="usagerecord",
            constraint=models.UniqueConstraint(
                fields=("user", "metric", "period_start"),
                name="unique_usage_per_period",
            ),
        ),
    ]
