"""Generate static/src/tokens.css from design/tonal/tokens.json.

The Tonal design system (design/tonal/README.md) is the source of truth for
colour roles, type, spacing, shape, elevation and state opacities. This turns it
into CSS custom properties — `:root` for the light theme, `.dark` for the dark
one — which tailwind.config.js and static/src/input.css consume. Run it after
editing tokens.json:

    python design/build_tokens.py && npm run build:css
"""

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent
tokens = json.loads((ROOT / "tonal" / "tokens.json").read_text())
OUT = ROOT.parent / "static" / "src" / "tokens.css"


def rgb_channels(value: str) -> str:
    value = value.lstrip("#")
    if len(value) in (3, 4):
        value = "".join(ch * 2 for ch in value)
    return " ".join(str(int(value[i : i + 2], 16)) for i in (0, 2, 4))


def block(selector: str, theme: str, extras: list[str]) -> str:
    lines = [f"{selector} {{"]
    for token in tokens["color"]["tokens"]:
        value = token["value"]
        value = value if isinstance(value, str) else value.get(theme, value["light"])
        lines.append(f"  --{token['name']}: {value};")
        lines.append(f"  --{token['name']}-rgb: {rgb_channels(value)};")
    lines += extras
    lines.append("}")
    return "\n".join(lines)


shared = []
for family in ("spacing", "radius", "shadow", "opacity"):
    for token in tokens[family]["tokens"]:
        shared.append(f"  --{token['name']}: {token['value']};")
for name, stack in tokens["type"]["families"].items():
    shared.append(f"  --font-{name}: {stack};")

css = "\n".join(
    [
        "/* GENERATED by design/build_tokens.py from design/tonal/tokens.json — do not edit. */",
        block(":root", "light", shared),
        "",
        block(".dark", "dark", []),
        "",
    ]
)
OUT.write_text(css)
print(f"wrote {OUT.relative_to(ROOT.parent)} ({len(tokens['color']['tokens'])} colour roles)")
