# Generated by Django 5.0.14 on 2026-09-04 23:45

import django.db.models.deletion
from django.db import migrations, models


def copy_description_to_highlights(apps, schema_editor):
    WorkExperience = apps.get_model("experience", "WorkExperience")
    ExperienceHighlight = apps.get_model("experience", "ExperienceHighlight")
    for experience in WorkExperience.objects.exclude(description=""):
        lines = [line.strip() for line in experience.description.splitlines() if line.strip()]
        ExperienceHighlight.objects.bulk_create(
            ExperienceHighlight(experience=experience, text=text[:500], order=order)
            for order, text in enumerate(lines)
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("experience", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExperienceHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlights",
                        to="experience.workexperience",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.RunPython(copy_description_to_highlights, noop_reverse),
        migrations.RemoveField(
            model_name="workexperience",
            name="description",
        ),
    ]
