# Generated by Django 5.0.14 on 2026-09-03 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("soft", "Soft skill"),
                            ("technical", "Technical skill"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Optional short label or emoji shown next to the category.",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "skill categories",
                "ordering": ["kind", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Beginner"),
                            (2, "Intermediate"),
                            (3, "Advanced"),
                            (4, "Expert"),
                        ],
                        default=2,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category__name", "-level", "name"],
            },
        ),
        migrations.AddConstraint(
            model_name="skillcategory",
            constraint=models.UniqueConstraint(
                fields=("name", "kind"), name="unique_category_per_kind"
            ),
        ),
        migrations.AddField(
            model_name="userskill",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_skills",
                to="skills.skillcategory",
            ),
        ),
        migrations.AddField(
            model_name="userskill",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="userskill",
            constraint=models.UniqueConstraint(
                fields=("user", "category", "name"),
                name="unique_skill_per_user_category",
            ),
        ),
    ]
