# Generated by Django 5.0.14 on 2026-09-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0002_tailoredresume"),
    ]

    operations = [
        migrations.AddField(
            model_name="tailoredresume",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tailoredresume",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Generating"),
                    ("completed", "Ready"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
